### ISSUE TITLE
Iniciar o ReadMe

### ISSUE THREAD

**Issue by caiosant** [TreinaDev/pagamentos-alpha#16]
Readme com informações essenciais sobre o projeto.

**Comment by jeffersondenilson** [comment]
Poderia também adicionar os sprints do #1 , [diagrama](https://docs.google.com/drawings/d/1JThfhFGx6O8p3lijoboJbZBGjQjlOXToAzejdqna3zs/edit?usp=sharing) e [preview](https://mepague.herokuapp.com)
